### ISSUE TITLE
Game crashed with "Bad Data Mod" Exception, sometimes immediately, sometimes after a few minutes

### ISSUE THREAD

**Issue by auximalia** [Woprok/AOE4-AdvancedGameSettings#12]
![image](https://user-images.githubusercontent.com/88620093/163371085-2749b6e8-828a-406c-9fb6-9cb57b1d63e7.png)
![image](https://user-images.githubusercontent.com/88620093/163371577-f1409952-d175-4d3c-9ff9-940579228425.png)
![image](https://user-images.githubusercontent.com/88620093/163371634-b4576717-a5c6-4fd5-9e23-25d0c7d2a134.png)
![image](https://user-images.githubusercontent.com/88620093/163371746-d5e3d4bc-9f36-4e66-9fb7-06650d0000b4.png)

**Comment by Woprok** [comment]
@auximalia 
I pushed small update, based on error I was able to find in my short testing.  If it happens again provide me with map, map seed & civilizations as this might be specific to certain conditions.

**Comment by auximalia** [comment]
@Woprok : Thanks a million for your respons! Your Mod is the most important one at all ;-)
I will have a try - and I will follow your instructions should an error occur.
Best greetings from Dresden

auxi

**Comment by ObiOneStenobi** [comment]
I have found another bug that causes the same error. To easily trigger it, just save the game. (otherwise it will trigger later in game).
It happens while using China. (I've not tested with all factions, only french and english and it works perfectly
![Age of Empires IV Screenshot 2022 04 25 - 20 43 48 89](https://user-images.githubusercontent.com/26001920/165154788-12a3daa9-0d9f-4c53-8056-07733c5dab26.png)
![Age of Empires IV Screenshot 2022 04 25 - 20 43 59 77](https://user-images.githubusercontent.com/26001920/165154794-61346789-dfe6-4fef-920f-55fbe7a19a10.png)
![Age of Empires IV Screenshot 2022 04 25 - 20 44 10 38](https://user-images.githubusercontent.com/26001920/165154799-149b55f2-4e45-4460-bfcd-81685e35734b.png)
)

**Comment by Woprok** [comment]
@auximalia @ObiOneStenobi I am not able to replicate it on current version that I am about to push out. If you are able to cause it again let me now. I will close this. Create new issue if you can make it happen again.
