### ISSUE TITLE
Not enough relics are spawning

### ISSUE THREAD

**Issue by fupespace** [Woprok/AOE4-AdvancedGameSettings#30]
Was playing a 2v2v2v2 match on Mega Random crafted map and only 5 relics spawned. This happened three more times and all games had 8 players. Its not the crafted map that has the issue because all relics spawn when using other mods. 

Thanks in advance.

**Comment by Woprok** [comment]
Interesting I will try to figure out why its happening.

**Comment by Woprok** [comment]
@fupespace I looked at it, and there is no reason for Relics to disappear from the map when my mod is active.

I never despawn relics or even touch them. It looks like this issue is with megarandom generation as I am not even able to replicate the map from seed where it happens based on replay I watched. 

I suggest you to report this to Relic as it's definitely issue with map generation
