### ISSUE TITLE
Game Simulation Speed - FPS

### ISSUE THREAD

**Issue by Gladifin** [Woprok/AOE4-AdvancedGameSettings#4]
Hi, i dont know how much is possible to do/fix. But slower speed unit fps is kinda horrible its like whole game lagging, is there anything that can be done to that or is it because of how game itself works? 
E: In internet play

**Comment by Gladifin** [comment]
Actualy it feels like game speeds dont work at all, even faster ones just lags and dont be rly faster.

**Comment by Woprok** [comment]
@Gladifin I cant do anything with that. That will be server lockstep issue to prevent desync,

**Comment by Woprok** [comment]
Game is not capable of altering simulation speed, amount of ticks in multiplayer environment. As this is only a mod, option for faster simulation is left in mainly for solo pve.
It's not possible for me to fix it as this issue is created by server / multiplayer connection that does not support faster ticks.
