### ISSUE TITLE
starting villagers bug

### ISSUE THREAD

**Issue by cliffture** [Woprok/AOE4-AdvancedGameSettings#50]
you got 1 more scout and 6 more villagers than your setting,,,

**Comment by Woprok** [comment]
Next time write more details, so I don't have to figure out which option and game mode is a problem.

AGS mode, Nomadic Settlement is spawning both prefab and script version of starting units. Issue will be fixed in next update... In meantime use Nomad AGS mode as that version is working correctly.

**Comment by SirMishaa** [comment]
Hello there, thank you for your work! 

Any idea when the issue will be fixed? It's kind of boring
I could make a PR, but I don't know well the modding of AOE 4 :/

**Comment by Woprok** [comment]
Nomad AGS should work fine with AI if you are playing it as multiplayer custom game (even if you are solo). AI behaves better with mods in multiplayer due to how AI connects to game...

Fix will be most likely in two weeks once I have again access to better PC... I had lot of problems trying to update mod recently, when I used my older notebook...

**Comment by Woprok** [comment]
Fixed in new update.
