### ISSUE TITLE
Request: Change Player Colors

### ISSUE THREAD

**Issue by MaxAlex200** [Woprok/AOE4-AdvancedGameSettings#8]
I attempted to do this myself, but there kept being errors in my code. Your mod is awesome and has so many options. Could you add the ability to change player color? The more the better. I attempted to do it with hex colors #1d1d1d [black] but haven't gotten it to work yet.

**Comment by MaxAlex200** [comment]
![PlayerCol](https://user-images.githubusercontent.com/99284302/162579488-b1da73f4-499c-4d33-946c-11fd149fcd1a.jpg)
I found that they exist in tuning_simulation, but was not able to clone the file or change the parameters.

**Comment by MaxAlex200** [comment]
![Black](https://user-images.githubusercontent.com/99284302/162592198-c39750d4-52ea-40e5-9cde-11be583a06ab.jpg)
I still haven't figured out how to change the shadows or minimap color or to build a dropdown box with this. But I went to paint and paint scheme and was able to change it.

**Comment by MaxAlex200** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2792060996

**Comment by MaxAlex200** [comment]
![mod](https://user-images.githubusercontent.com/99284302/162600835-212bbc0a-9752-4d96-a743-e55da5bfc27b.png)
Burgundy

**Comment by MaxAlex200** [comment]
![mod](https://user-images.githubusercontent.com/99284302/162617565-0ae9265d-be88-40dc-9c2d-61e1dc3239c4.png)
Play as Gold

**Comment by MaxAlex200** [comment]
![mod](https://user-images.githubusercontent.com/99284302/162617618-d853550d-54b4-44f8-b8f4-e87af3a8a737.png)

**Comment by Woprok** [comment]
@MaxAlex200 
First If it looked like I ignored it then that was not true, I was aware of this, but it had very low priority as Its coming officially by Relic in summer update.

Gamemode script cant change attribute values, so the only thing I could add is swapping of existing colors. 

As gamemode is unable to change player slot UI or add new elements to it, its really limiting to add player specific options as it  is required by host to set it up, which is reason why I didn't even try to pursue adding swapping until now.

Anyway I added ability to swap colors associated with slots, that will also affect any tuning pack that changes tuning data to have specific colors. So if anyone creates tuning pack that changes all colors associated with slots to different you can swap them in lobby between players.

This was added only because I needed code that forces players to get correct color after their diplomacy relations change as Relic is unlikely to fix that issue anytime soon.
